class store {
    shoeList = [
        {
            id : null,
            productName : 'Nike Air VaporMax 3',
            category : 'Men',
            size : '9',
            colour : 'Gry/Wht',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'adidas Originals OZEREGO',
            category : 'Women',
            size : '4',
            colour : 'Black',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'Nike Air Max 95 SE',
            category : 'Men',
            size : '10',
            colour : 'Blue',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'Nike Air VaporMax 2019',
            category : 'Junior',
            size : '3',
            colour : 'Black',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'Nike Air VaporMax 3',
            category : 'Men',
            size : '9',
            colour : 'Gry/Wht',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'adidas Originals Flux',
            category : 'Women',
            size : '5',
            colour : 'Blue',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'Nike Air Max 95',
            category : 'Men',
            size : '11',
            colour : 'Red',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'Nike Air Max 98',
            category : 'Junior',
            size : '3',
            colour : 'Black',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'Nike Air VaporMax 1',
            category : 'Men',
            size : '11',
            colour : 'Gry',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'adidas Originals ZX',
            category : 'Women',
            size : '5',
            colour : 'White',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'Nike Air Max 97',
            category : 'Men',
            size : '8',
            colour : 'Red',
            status : '',
            customerInitials : '',
        },
        {
            id : null,
            productName : 'Nike Air VaporMax 2018',
            category : 'Junior',
            size : '2',
            colour : 'Black',
            status : '',
            customerInitials : '',
        },
    ]
}

export default new store();